<?php
return [
    "this" => "Privacy Policy",
    "t1" => 'The operators of these sites take the protection of personal data very seriously. We treat your personal data confidentially and in accordance with the data protection legislation and this Privacy Policy.
             <br>
              The use of our website is usually possible without providing personal information. If any personal data (such as name, address or email address) is collected, it is as far as possible on a voluntary basis. This data is not passed to third-parties without your express consent.
             <br>
              We point out that data transmission over the Internet (for example, when communicating via e-mail) can have security gaps. A complete protection of data against unauthorized access by third parties is impossible.',
    "analytics" => 'Privacy Statement for the Use of Google Analytics',
    "t2" => 'This website uses functions of the web analytics service Google Analytics. Provider is Google Inc. 1600 Amphitheatre Parkway Mountain View, CA 94043. Google Analytics uses "cookies". These are text files that are stored on your computer and enable analysis of your use of the website. The information generated by the cookie about your use of this website are usually transferred to a Google server in the USA and stored there.
             <br>
             In case of activation of the IP anonymization on this website your IP address from Google will be truncated within Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases will the full IP address transferred to a Google server in the USA and shortened there. On behalf of the operator of this website Google will use this information to evaluate your use of the website, compile reports on website activity and provide other with the website and internet related services to the website operator. The as part of Google Analytics from your browser sent IP-address will not be merged with other data from Google.
             <br>
             You may refuse the use of cookies by adjusting your browser software; however, we point out that you can in this case not use all features of this website to their full extent. You can also prevent the data generated by the cookie about your use of the website (incl. Your IP address) to Google and the processing of these data by Google, by downloading and installing the browser plugin available at the following link: <a href="http://tools.google.com/dlpage/gaoptout?hl=de" target="_blank">http://tools.google.com/dlpage/gaoptout?hl=de</a>',
    "twitter" => 'Privacy Statement for the Use of Twitter',
    "t3" => 'Functions of the Twitter service are integrated on our sites. These functions are offered by Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA. Through the use of Twitter and the "Re-Tweet" function, the web pages you visit are linked to your Twitter account and made available to other users. This data is also transmitted to Twitter. We point out that we as providers of this website no knowledge of the content that is transmitted data and use them through Twitter. For more information, please see the privacy statement of Twitter at <a href="http://twitter.com/privacy" target="_blank">http://twitter.com/privacy</a>.
             <br>
             You can change your Twitter privacy settings at: <a href="http://twitter.com/account/settings" target="_blank">http://twitter.com/account/settings</a>',
    "als" => 'Enquiry, erasure and blocking',
    "t4" => ' You always have the right to get information about your stored personal data, its origin and destination and the purpose of the data processing free of charge and the right to correct, block or delete this data. For this purpose, as well as other questions relating to personal data you can contact us at the e-mail address stated in the imprint at any time.',
    "t5" => 'The websites make use of so-called cookies. Cookies do not harm your computer and do not contain viruses. Cookies are used to make our offer more user-friendly, effective and safer. Cookies are small text files that are stored on your computer and saved by your browser.
             <br>
             Most of the cookies we use are so-called "session cookies". They are automatically deleted after your visit. Other cookies remain on your device memory until you delete them. These cookies allow us to recognize your browser the next time you visit.
             <br>
             You can configure your browser so that you are informed about the use of cookies and enable cookies in individual cases only, activate the acceptance of cookies for specific cases or generally decline the use, and the automatic deletion of cookies when you close the browser. Upon deactivation of cookies, the functionality of this site will be limited.',
    "t6" => 'The provider of the pages automatically collects and stores information in so-called server log files, which your browser automatically transmits to us. These are:
             <br><br>
             Browser type / browser version<br>
             Operating system used<br>
             Referrer URL<br>
             Host name of accessing computer<br>
             Time of server request<br>
             <br><br>
             <br>
             These data are not assignable to specific individuals. A compilation of this data with other data sources is not made. We reserve the right to examine this data retrospectively when concrete evidence of unlawful use are known.'

];